// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/contracts/infra.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfraResourceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Workspace     string                 `protobuf:"bytes,3,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Settings      *structpb.Struct       `protobuf:"bytes,5,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfraResourceConfig) Reset() {
	*x = InfraResourceConfig{}
	mi := &file_internal_contracts_infra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfraResourceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfraResourceConfig) ProtoMessage() {}

func (x *InfraResourceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_infra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfraResourceConfig.ProtoReflect.Descriptor instead.
func (*InfraResourceConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_infra_proto_rawDescGZIP(), []int{0}
}

func (x *InfraResourceConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *InfraResourceConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *InfraResourceConfig) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *InfraResourceConfig) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *InfraResourceConfig) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

type ContainerServiceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Workspace     string                 `protobuf:"bytes,3,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Ports         []int32                `protobuf:"varint,5,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	Env           map[string]string      `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Replicas      int32                  `protobuf:"varint,7,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Settings      *structpb.Struct       `protobuf:"bytes,9,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerServiceConfig) Reset() {
	*x = ContainerServiceConfig{}
	mi := &file_internal_contracts_infra_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerServiceConfig) ProtoMessage() {}

func (x *ContainerServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_infra_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerServiceConfig.ProtoReflect.Descriptor instead.
func (*ContainerServiceConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_infra_proto_rawDescGZIP(), []int{1}
}

func (x *ContainerServiceConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ContainerServiceConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ContainerServiceConfig) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *ContainerServiceConfig) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerServiceConfig) GetPorts() []int32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ContainerServiceConfig) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ContainerServiceConfig) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *ContainerServiceConfig) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ContainerServiceConfig) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

type K8SClusterConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Workspace     string                 `protobuf:"bytes,3,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	NodeCount     int32                  `protobuf:"varint,5,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	NodeSize      string                 `protobuf:"bytes,6,opt,name=node_size,json=nodeSize,proto3" json:"node_size,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Settings      *structpb.Struct       `protobuf:"bytes,8,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SClusterConfig) Reset() {
	*x = K8SClusterConfig{}
	mi := &file_internal_contracts_infra_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SClusterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SClusterConfig) ProtoMessage() {}

func (x *K8SClusterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_infra_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SClusterConfig.ProtoReflect.Descriptor instead.
func (*K8SClusterConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_infra_proto_rawDescGZIP(), []int{2}
}

func (x *K8SClusterConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *K8SClusterConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *K8SClusterConfig) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *K8SClusterConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *K8SClusterConfig) GetNodeCount() int32 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *K8SClusterConfig) GetNodeSize() string {
	if x != nil {
		return x.NodeSize
	}
	return ""
}

func (x *K8SClusterConfig) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *K8SClusterConfig) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

type DatabaseConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Workspace     string                 `protobuf:"bytes,3,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Engine        string                 `protobuf:"bytes,4,opt,name=engine,proto3" json:"engine,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Size          string                 `protobuf:"bytes,6,opt,name=size,proto3" json:"size,omitempty"`
	StorageGb     int32                  `protobuf:"varint,7,opt,name=storage_gb,json=storageGb,proto3" json:"storage_gb,omitempty"`
	MultiAz       bool                   `protobuf:"varint,8,opt,name=multi_az,json=multiAz,proto3" json:"multi_az,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Settings      *structpb.Struct       `protobuf:"bytes,10,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseConfig) Reset() {
	*x = DatabaseConfig{}
	mi := &file_internal_contracts_infra_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseConfig) ProtoMessage() {}

func (x *DatabaseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_infra_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseConfig.ProtoReflect.Descriptor instead.
func (*DatabaseConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_infra_proto_rawDescGZIP(), []int{3}
}

func (x *DatabaseConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *DatabaseConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *DatabaseConfig) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *DatabaseConfig) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *DatabaseConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DatabaseConfig) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *DatabaseConfig) GetStorageGb() int32 {
	if x != nil {
		return x.StorageGb
	}
	return 0
}

func (x *DatabaseConfig) GetMultiAz() bool {
	if x != nil {
		return x.MultiAz
	}
	return false
}

func (x *DatabaseConfig) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *DatabaseConfig) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

type CacheConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Workspace     string                 `protobuf:"bytes,3,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Engine        string                 `protobuf:"bytes,4,opt,name=engine,proto3" json:"engine,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Size          string                 `protobuf:"bytes,6,opt,name=size,proto3" json:"size,omitempty"`
	Nodes         int32                  `protobuf:"varint,7,opt,name=nodes,proto3" json:"nodes,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Settings      *structpb.Struct       `protobuf:"bytes,9,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheConfig) Reset() {
	*x = CacheConfig{}
	mi := &file_internal_contracts_infra_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheConfig) ProtoMessage() {}

func (x *CacheConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_infra_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheConfig.ProtoReflect.Descriptor instead.
func (*CacheConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_infra_proto_rawDescGZIP(), []int{4}
}

func (x *CacheConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CacheConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CacheConfig) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *CacheConfig) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *CacheConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CacheConfig) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *CacheConfig) GetNodes() int32 {
	if x != nil {
		return x.Nodes
	}
	return 0
}

func (x *CacheConfig) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CacheConfig) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

type VPCConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Provider          string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Region            string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Workspace         string                 `protobuf:"bytes,3,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Cidr              string                 `protobuf:"bytes,4,opt,name=cidr,proto3" json:"cidr,omitempty"`
	AvailabilityZones []string               `protobuf:"bytes,5,rep,name=availability_zones,json=availabilityZones,proto3" json:"availability_zones,omitempty"`
	Labels            map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Settings          *structpb.Struct       `protobuf:"bytes,7,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VPCConfig) Reset() {
	*x = VPCConfig{}
	mi := &file_internal_contracts_infra_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VPCConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VPCConfig) ProtoMessage() {}

func (x *VPCConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_infra_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VPCConfig.ProtoReflect.Descriptor instead.
func (*VPCConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_infra_proto_rawDescGZIP(), []int{5}
}

func (x *VPCConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *VPCConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *VPCConfig) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *VPCConfig) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *VPCConfig) GetAvailabilityZones() []string {
	if x != nil {
		return x.AvailabilityZones
	}
	return nil
}

func (x *VPCConfig) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *VPCConfig) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

type LoadBalancerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Workspace     string                 `protobuf:"bytes,3,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Scheme        string                 `protobuf:"bytes,4,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Ports         []int32                `protobuf:"varint,5,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Settings      *structpb.Struct       `protobuf:"bytes,7,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadBalancerConfig) Reset() {
	*x = LoadBalancerConfig{}
	mi := &file_internal_contracts_infra_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadBalancerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBalancerConfig) ProtoMessage() {}

func (x *LoadBalancerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_infra_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadBalancerConfig.ProtoReflect.Descriptor instead.
func (*LoadBalancerConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_infra_proto_rawDescGZIP(), []int{6}
}

func (x *LoadBalancerConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LoadBalancerConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *LoadBalancerConfig) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *LoadBalancerConfig) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *LoadBalancerConfig) GetPorts() []int32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *LoadBalancerConfig) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *LoadBalancerConfig) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

type DNSConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Workspace     string                 `protobuf:"bytes,3,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Zone          string                 `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`
	Record        string                 `protobuf:"bytes,5,opt,name=record,proto3" json:"record,omitempty"`
	Target        string                 `protobuf:"bytes,6,opt,name=target,proto3" json:"target,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Settings      *structpb.Struct       `protobuf:"bytes,8,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSConfig) Reset() {
	*x = DNSConfig{}
	mi := &file_internal_contracts_infra_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSConfig) ProtoMessage() {}

func (x *DNSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_infra_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSConfig.ProtoReflect.Descriptor instead.
func (*DNSConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_infra_proto_rawDescGZIP(), []int{7}
}

func (x *DNSConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *DNSConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *DNSConfig) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *DNSConfig) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *DNSConfig) GetRecord() string {
	if x != nil {
		return x.Record
	}
	return ""
}

func (x *DNSConfig) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *DNSConfig) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *DNSConfig) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

type RegistryConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Workspace     string                 `protobuf:"bytes,3,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Public        bool                   `protobuf:"varint,5,opt,name=public,proto3" json:"public,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Settings      *structpb.Struct       `protobuf:"bytes,7,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryConfig) Reset() {
	*x = RegistryConfig{}
	mi := &file_internal_contracts_infra_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryConfig) ProtoMessage() {}

func (x *RegistryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_infra_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryConfig.ProtoReflect.Descriptor instead.
func (*RegistryConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_infra_proto_rawDescGZIP(), []int{8}
}

func (x *RegistryConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *RegistryConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RegistryConfig) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *RegistryConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegistryConfig) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *RegistryConfig) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegistryConfig) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

type APIGatewayConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Workspace     string                 `protobuf:"bytes,3,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Routes        []string               `protobuf:"bytes,5,rep,name=routes,proto3" json:"routes,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Settings      *structpb.Struct       `protobuf:"bytes,7,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIGatewayConfig) Reset() {
	*x = APIGatewayConfig{}
	mi := &file_internal_contracts_infra_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIGatewayConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIGatewayConfig) ProtoMessage() {}

func (x *APIGatewayConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_infra_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIGatewayConfig.ProtoReflect.Descriptor instead.
func (*APIGatewayConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_infra_proto_rawDescGZIP(), []int{9}
}

func (x *APIGatewayConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *APIGatewayConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *APIGatewayConfig) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *APIGatewayConfig) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *APIGatewayConfig) GetRoutes() []string {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *APIGatewayConfig) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *APIGatewayConfig) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

type FirewallConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Workspace     string                 `protobuf:"bytes,3,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Ingress       []string               `protobuf:"bytes,4,rep,name=ingress,proto3" json:"ingress,omitempty"`
	Egress        []string               `protobuf:"bytes,5,rep,name=egress,proto3" json:"egress,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Settings      *structpb.Struct       `protobuf:"bytes,7,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirewallConfig) Reset() {
	*x = FirewallConfig{}
	mi := &file_internal_contracts_infra_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirewallConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirewallConfig) ProtoMessage() {}

func (x *FirewallConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_infra_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirewallConfig.ProtoReflect.Descriptor instead.
func (*FirewallConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_infra_proto_rawDescGZIP(), []int{10}
}

func (x *FirewallConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *FirewallConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *FirewallConfig) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *FirewallConfig) GetIngress() []string {
	if x != nil {
		return x.Ingress
	}
	return nil
}

func (x *FirewallConfig) GetEgress() []string {
	if x != nil {
		return x.Egress
	}
	return nil
}

func (x *FirewallConfig) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *FirewallConfig) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

type IAMRoleConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Workspace     string                 `protobuf:"bytes,3,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Policies      []string               `protobuf:"bytes,5,rep,name=policies,proto3" json:"policies,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Settings      *structpb.Struct       `protobuf:"bytes,7,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IAMRoleConfig) Reset() {
	*x = IAMRoleConfig{}
	mi := &file_internal_contracts_infra_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IAMRoleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IAMRoleConfig) ProtoMessage() {}

func (x *IAMRoleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_infra_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IAMRoleConfig.ProtoReflect.Descriptor instead.
func (*IAMRoleConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_infra_proto_rawDescGZIP(), []int{11}
}

func (x *IAMRoleConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *IAMRoleConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *IAMRoleConfig) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *IAMRoleConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IAMRoleConfig) GetPolicies() []string {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *IAMRoleConfig) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *IAMRoleConfig) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

type StorageConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Workspace     string                 `protobuf:"bytes,3,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Class         string                 `protobuf:"bytes,5,opt,name=class,proto3" json:"class,omitempty"`
	Versioning    bool                   `protobuf:"varint,6,opt,name=versioning,proto3" json:"versioning,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Settings      *structpb.Struct       `protobuf:"bytes,8,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageConfig) Reset() {
	*x = StorageConfig{}
	mi := &file_internal_contracts_infra_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageConfig) ProtoMessage() {}

func (x *StorageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_infra_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageConfig.ProtoReflect.Descriptor instead.
func (*StorageConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_infra_proto_rawDescGZIP(), []int{12}
}

func (x *StorageConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *StorageConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *StorageConfig) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *StorageConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StorageConfig) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *StorageConfig) GetVersioning() bool {
	if x != nil {
		return x.Versioning
	}
	return false
}

func (x *StorageConfig) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *StorageConfig) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

type CertificateConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Provider        string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Region          string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Workspace       string                 `protobuf:"bytes,3,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Domain          string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	SubjectAltNames []string               `protobuf:"bytes,5,rep,name=subject_alt_names,json=subjectAltNames,proto3" json:"subject_alt_names,omitempty"`
	Labels          map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Settings        *structpb.Struct       `protobuf:"bytes,7,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CertificateConfig) Reset() {
	*x = CertificateConfig{}
	mi := &file_internal_contracts_infra_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateConfig) ProtoMessage() {}

func (x *CertificateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_infra_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateConfig.ProtoReflect.Descriptor instead.
func (*CertificateConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_infra_proto_rawDescGZIP(), []int{13}
}

func (x *CertificateConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CertificateConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CertificateConfig) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *CertificateConfig) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CertificateConfig) GetSubjectAltNames() []string {
	if x != nil {
		return x.SubjectAltNames
	}
	return nil
}

func (x *CertificateConfig) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CertificateConfig) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

var File_internal_contracts_infra_proto protoreflect.FileDescriptor

const file_internal_contracts_infra_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/contracts/infra.proto\x12\x19workflow.plugins.infra.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xab\x02\n" +
	"\x13InfraResourceConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1c\n" +
	"\tworkspace\x18\x03 \x01(\tR\tworkspace\x12R\n" +
	"\x06labels\x18\x04 \x03(\v2:.workflow.plugins.infra.v1.InfraResourceConfig.LabelsEntryR\x06labels\x123\n" +
	"\bsettings\x18\x05 \x01(\v2\x17.google.protobuf.StructR\bsettings\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xff\x03\n" +
	"\x16ContainerServiceConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1c\n" +
	"\tworkspace\x18\x03 \x01(\tR\tworkspace\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x14\n" +
	"\x05ports\x18\x05 \x03(\x05R\x05ports\x12L\n" +
	"\x03env\x18\x06 \x03(\v2:.workflow.plugins.infra.v1.ContainerServiceConfig.EnvEntryR\x03env\x12\x1a\n" +
	"\breplicas\x18\a \x01(\x05R\breplicas\x12U\n" +
	"\x06labels\x18\b \x03(\v2=.workflow.plugins.infra.v1.ContainerServiceConfig.LabelsEntryR\x06labels\x123\n" +
	"\bsettings\x18\t \x01(\v2\x17.google.protobuf.StructR\bsettings\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfb\x02\n" +
	"\x10K8SClusterConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1c\n" +
	"\tworkspace\x18\x03 \x01(\tR\tworkspace\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"node_count\x18\x05 \x01(\x05R\tnodeCount\x12\x1b\n" +
	"\tnode_size\x18\x06 \x01(\tR\bnodeSize\x12O\n" +
	"\x06labels\x18\a \x03(\v27.workflow.plugins.infra.v1.K8SClusterConfig.LabelsEntryR\x06labels\x123\n" +
	"\bsettings\x18\b \x01(\v2\x17.google.protobuf.StructR\bsettings\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa1\x03\n" +
	"\x0eDatabaseConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1c\n" +
	"\tworkspace\x18\x03 \x01(\tR\tworkspace\x12\x16\n" +
	"\x06engine\x18\x04 \x01(\tR\x06engine\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x12\n" +
	"\x04size\x18\x06 \x01(\tR\x04size\x12\x1d\n" +
	"\n" +
	"storage_gb\x18\a \x01(\x05R\tstorageGb\x12\x19\n" +
	"\bmulti_az\x18\b \x01(\bR\amultiAz\x12M\n" +
	"\x06labels\x18\t \x03(\v25.workflow.plugins.infra.v1.DatabaseConfig.LabelsEntryR\x06labels\x123\n" +
	"\bsettings\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\bsettings\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf7\x02\n" +
	"\vCacheConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1c\n" +
	"\tworkspace\x18\x03 \x01(\tR\tworkspace\x12\x16\n" +
	"\x06engine\x18\x04 \x01(\tR\x06engine\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x12\n" +
	"\x04size\x18\x06 \x01(\tR\x04size\x12\x14\n" +
	"\x05nodes\x18\a \x01(\x05R\x05nodes\x12J\n" +
	"\x06labels\x18\b \x03(\v22.workflow.plugins.infra.v1.CacheConfig.LabelsEntryR\x06labels\x123\n" +
	"\bsettings\x18\t \x01(\v2\x17.google.protobuf.StructR\bsettings\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xda\x02\n" +
	"\tVPCConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1c\n" +
	"\tworkspace\x18\x03 \x01(\tR\tworkspace\x12\x12\n" +
	"\x04cidr\x18\x04 \x01(\tR\x04cidr\x12-\n" +
	"\x12availability_zones\x18\x05 \x03(\tR\x11availabilityZones\x12H\n" +
	"\x06labels\x18\x06 \x03(\v20.workflow.plugins.infra.v1.VPCConfig.LabelsEntryR\x06labels\x123\n" +
	"\bsettings\x18\a \x01(\v2\x17.google.protobuf.StructR\bsettings\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd7\x02\n" +
	"\x12LoadBalancerConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1c\n" +
	"\tworkspace\x18\x03 \x01(\tR\tworkspace\x12\x16\n" +
	"\x06scheme\x18\x04 \x01(\tR\x06scheme\x12\x14\n" +
	"\x05ports\x18\x05 \x03(\x05R\x05ports\x12Q\n" +
	"\x06labels\x18\x06 \x03(\v29.workflow.plugins.infra.v1.LoadBalancerConfig.LabelsEntryR\x06labels\x123\n" +
	"\bsettings\x18\a \x01(\v2\x17.google.protobuf.StructR\bsettings\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdb\x02\n" +
	"\tDNSConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1c\n" +
	"\tworkspace\x18\x03 \x01(\tR\tworkspace\x12\x12\n" +
	"\x04zone\x18\x04 \x01(\tR\x04zone\x12\x16\n" +
	"\x06record\x18\x05 \x01(\tR\x06record\x12\x16\n" +
	"\x06target\x18\x06 \x01(\tR\x06target\x12H\n" +
	"\x06labels\x18\a \x03(\v20.workflow.plugins.infra.v1.DNSConfig.LabelsEntryR\x06labels\x123\n" +
	"\bsettings\x18\b \x01(\v2\x17.google.protobuf.StructR\bsettings\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcd\x02\n" +
	"\x0eRegistryConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1c\n" +
	"\tworkspace\x18\x03 \x01(\tR\tworkspace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06public\x18\x05 \x01(\bR\x06public\x12M\n" +
	"\x06labels\x18\x06 \x03(\v25.workflow.plugins.infra.v1.RegistryConfig.LabelsEntryR\x06labels\x123\n" +
	"\bsettings\x18\a \x01(\v2\x17.google.protobuf.StructR\bsettings\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd9\x02\n" +
	"\x10APIGatewayConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1c\n" +
	"\tworkspace\x18\x03 \x01(\tR\tworkspace\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06routes\x18\x05 \x03(\tR\x06routes\x12O\n" +
	"\x06labels\x18\x06 \x03(\v27.workflow.plugins.infra.v1.APIGatewayConfig.LabelsEntryR\x06labels\x123\n" +
	"\bsettings\x18\a \x01(\v2\x17.google.protobuf.StructR\bsettings\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd3\x02\n" +
	"\x0eFirewallConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1c\n" +
	"\tworkspace\x18\x03 \x01(\tR\tworkspace\x12\x18\n" +
	"\aingress\x18\x04 \x03(\tR\aingress\x12\x16\n" +
	"\x06egress\x18\x05 \x03(\tR\x06egress\x12M\n" +
	"\x06labels\x18\x06 \x03(\v25.workflow.plugins.infra.v1.FirewallConfig.LabelsEntryR\x06labels\x123\n" +
	"\bsettings\x18\a \x01(\v2\x17.google.protobuf.StructR\bsettings\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcf\x02\n" +
	"\rIAMRoleConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1c\n" +
	"\tworkspace\x18\x03 \x01(\tR\tworkspace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\bpolicies\x18\x05 \x03(\tR\bpolicies\x12L\n" +
	"\x06labels\x18\x06 \x03(\v24.workflow.plugins.infra.v1.IAMRoleConfig.LabelsEntryR\x06labels\x123\n" +
	"\bsettings\x18\a \x01(\v2\x17.google.protobuf.StructR\bsettings\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe9\x02\n" +
	"\rStorageConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1c\n" +
	"\tworkspace\x18\x03 \x01(\tR\tworkspace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05class\x18\x05 \x01(\tR\x05class\x12\x1e\n" +
	"\n" +
	"versioning\x18\x06 \x01(\bR\n" +
	"versioning\x12L\n" +
	"\x06labels\x18\a \x03(\v24.workflow.plugins.infra.v1.StorageConfig.LabelsEntryR\x06labels\x123\n" +
	"\bsettings\x18\b \x01(\v2\x17.google.protobuf.StructR\bsettings\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xeb\x02\n" +
	"\x11CertificateConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1c\n" +
	"\tworkspace\x18\x03 \x01(\tR\tworkspace\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12*\n" +
	"\x11subject_alt_names\x18\x05 \x03(\tR\x0fsubjectAltNames\x12P\n" +
	"\x06labels\x18\x06 \x03(\v28.workflow.plugins.infra.v1.CertificateConfig.LabelsEntryR\x06labels\x123\n" +
	"\bsettings\x18\a \x01(\v2\x17.google.protobuf.StructR\bsettings\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BKZIgithub.com/GoCodeAlone/workflow-plugin-infra/internal/contracts;contractsb\x06proto3"

var (
	file_internal_contracts_infra_proto_rawDescOnce sync.Once
	file_internal_contracts_infra_proto_rawDescData []byte
)

func file_internal_contracts_infra_proto_rawDescGZIP() []byte {
	file_internal_contracts_infra_proto_rawDescOnce.Do(func() {
		file_internal_contracts_infra_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_contracts_infra_proto_rawDesc), len(file_internal_contracts_infra_proto_rawDesc)))
	})
	return file_internal_contracts_infra_proto_rawDescData
}

var file_internal_contracts_infra_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_internal_contracts_infra_proto_goTypes = []any{
	(*InfraResourceConfig)(nil),    // 0: workflow.plugins.infra.v1.InfraResourceConfig
	(*ContainerServiceConfig)(nil), // 1: workflow.plugins.infra.v1.ContainerServiceConfig
	(*K8SClusterConfig)(nil),       // 2: workflow.plugins.infra.v1.K8SClusterConfig
	(*DatabaseConfig)(nil),         // 3: workflow.plugins.infra.v1.DatabaseConfig
	(*CacheConfig)(nil),            // 4: workflow.plugins.infra.v1.CacheConfig
	(*VPCConfig)(nil),              // 5: workflow.plugins.infra.v1.VPCConfig
	(*LoadBalancerConfig)(nil),     // 6: workflow.plugins.infra.v1.LoadBalancerConfig
	(*DNSConfig)(nil),              // 7: workflow.plugins.infra.v1.DNSConfig
	(*RegistryConfig)(nil),         // 8: workflow.plugins.infra.v1.RegistryConfig
	(*APIGatewayConfig)(nil),       // 9: workflow.plugins.infra.v1.APIGatewayConfig
	(*FirewallConfig)(nil),         // 10: workflow.plugins.infra.v1.FirewallConfig
	(*IAMRoleConfig)(nil),          // 11: workflow.plugins.infra.v1.IAMRoleConfig
	(*StorageConfig)(nil),          // 12: workflow.plugins.infra.v1.StorageConfig
	(*CertificateConfig)(nil),      // 13: workflow.plugins.infra.v1.CertificateConfig
	nil,                            // 14: workflow.plugins.infra.v1.InfraResourceConfig.LabelsEntry
	nil,                            // 15: workflow.plugins.infra.v1.ContainerServiceConfig.EnvEntry
	nil,                            // 16: workflow.plugins.infra.v1.ContainerServiceConfig.LabelsEntry
	nil,                            // 17: workflow.plugins.infra.v1.K8SClusterConfig.LabelsEntry
	nil,                            // 18: workflow.plugins.infra.v1.DatabaseConfig.LabelsEntry
	nil,                            // 19: workflow.plugins.infra.v1.CacheConfig.LabelsEntry
	nil,                            // 20: workflow.plugins.infra.v1.VPCConfig.LabelsEntry
	nil,                            // 21: workflow.plugins.infra.v1.LoadBalancerConfig.LabelsEntry
	nil,                            // 22: workflow.plugins.infra.v1.DNSConfig.LabelsEntry
	nil,                            // 23: workflow.plugins.infra.v1.RegistryConfig.LabelsEntry
	nil,                            // 24: workflow.plugins.infra.v1.APIGatewayConfig.LabelsEntry
	nil,                            // 25: workflow.plugins.infra.v1.FirewallConfig.LabelsEntry
	nil,                            // 26: workflow.plugins.infra.v1.IAMRoleConfig.LabelsEntry
	nil,                            // 27: workflow.plugins.infra.v1.StorageConfig.LabelsEntry
	nil,                            // 28: workflow.plugins.infra.v1.CertificateConfig.LabelsEntry
	(*structpb.Struct)(nil),        // 29: google.protobuf.Struct
}
var file_internal_contracts_infra_proto_depIdxs = []int32{
	14, // 0: workflow.plugins.infra.v1.InfraResourceConfig.labels:type_name -> workflow.plugins.infra.v1.InfraResourceConfig.LabelsEntry
	29, // 1: workflow.plugins.infra.v1.InfraResourceConfig.settings:type_name -> google.protobuf.Struct
	15, // 2: workflow.plugins.infra.v1.ContainerServiceConfig.env:type_name -> workflow.plugins.infra.v1.ContainerServiceConfig.EnvEntry
	16, // 3: workflow.plugins.infra.v1.ContainerServiceConfig.labels:type_name -> workflow.plugins.infra.v1.ContainerServiceConfig.LabelsEntry
	29, // 4: workflow.plugins.infra.v1.ContainerServiceConfig.settings:type_name -> google.protobuf.Struct
	17, // 5: workflow.plugins.infra.v1.K8SClusterConfig.labels:type_name -> workflow.plugins.infra.v1.K8SClusterConfig.LabelsEntry
	29, // 6: workflow.plugins.infra.v1.K8SClusterConfig.settings:type_name -> google.protobuf.Struct
	18, // 7: workflow.plugins.infra.v1.DatabaseConfig.labels:type_name -> workflow.plugins.infra.v1.DatabaseConfig.LabelsEntry
	29, // 8: workflow.plugins.infra.v1.DatabaseConfig.settings:type_name -> google.protobuf.Struct
	19, // 9: workflow.plugins.infra.v1.CacheConfig.labels:type_name -> workflow.plugins.infra.v1.CacheConfig.LabelsEntry
	29, // 10: workflow.plugins.infra.v1.CacheConfig.settings:type_name -> google.protobuf.Struct
	20, // 11: workflow.plugins.infra.v1.VPCConfig.labels:type_name -> workflow.plugins.infra.v1.VPCConfig.LabelsEntry
	29, // 12: workflow.plugins.infra.v1.VPCConfig.settings:type_name -> google.protobuf.Struct
	21, // 13: workflow.plugins.infra.v1.LoadBalancerConfig.labels:type_name -> workflow.plugins.infra.v1.LoadBalancerConfig.LabelsEntry
	29, // 14: workflow.plugins.infra.v1.LoadBalancerConfig.settings:type_name -> google.protobuf.Struct
	22, // 15: workflow.plugins.infra.v1.DNSConfig.labels:type_name -> workflow.plugins.infra.v1.DNSConfig.LabelsEntry
	29, // 16: workflow.plugins.infra.v1.DNSConfig.settings:type_name -> google.protobuf.Struct
	23, // 17: workflow.plugins.infra.v1.RegistryConfig.labels:type_name -> workflow.plugins.infra.v1.RegistryConfig.LabelsEntry
	29, // 18: workflow.plugins.infra.v1.RegistryConfig.settings:type_name -> google.protobuf.Struct
	24, // 19: workflow.plugins.infra.v1.APIGatewayConfig.labels:type_name -> workflow.plugins.infra.v1.APIGatewayConfig.LabelsEntry
	29, // 20: workflow.plugins.infra.v1.APIGatewayConfig.settings:type_name -> google.protobuf.Struct
	25, // 21: workflow.plugins.infra.v1.FirewallConfig.labels:type_name -> workflow.plugins.infra.v1.FirewallConfig.LabelsEntry
	29, // 22: workflow.plugins.infra.v1.FirewallConfig.settings:type_name -> google.protobuf.Struct
	26, // 23: workflow.plugins.infra.v1.IAMRoleConfig.labels:type_name -> workflow.plugins.infra.v1.IAMRoleConfig.LabelsEntry
	29, // 24: workflow.plugins.infra.v1.IAMRoleConfig.settings:type_name -> google.protobuf.Struct
	27, // 25: workflow.plugins.infra.v1.StorageConfig.labels:type_name -> workflow.plugins.infra.v1.StorageConfig.LabelsEntry
	29, // 26: workflow.plugins.infra.v1.StorageConfig.settings:type_name -> google.protobuf.Struct
	28, // 27: workflow.plugins.infra.v1.CertificateConfig.labels:type_name -> workflow.plugins.infra.v1.CertificateConfig.LabelsEntry
	29, // 28: workflow.plugins.infra.v1.CertificateConfig.settings:type_name -> google.protobuf.Struct
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_internal_contracts_infra_proto_init() }
func file_internal_contracts_infra_proto_init() {
	if File_internal_contracts_infra_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_contracts_infra_proto_rawDesc), len(file_internal_contracts_infra_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_contracts_infra_proto_goTypes,
		DependencyIndexes: file_internal_contracts_infra_proto_depIdxs,
		MessageInfos:      file_internal_contracts_infra_proto_msgTypes,
	}.Build()
	File_internal_contracts_infra_proto = out.File
	file_internal_contracts_infra_proto_goTypes = nil
	file_internal_contracts_infra_proto_depIdxs = nil
}
