// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal/contracts/infra_admin.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfraAdminContributionConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Module        string                 `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	RenderMode    string                 `protobuf:"bytes,7,opt,name=render_mode,json=renderMode,proto3" json:"render_mode,omitempty"`
	AppContext    string                 `protobuf:"bytes,8,opt,name=app_context,json=appContext,proto3" json:"app_context,omitempty"`
	Permissions   []string               `protobuf:"bytes,9,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfraAdminContributionConfig) Reset() {
	*x = InfraAdminContributionConfig{}
	mi := &file_internal_contracts_infra_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfraAdminContributionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfraAdminContributionConfig) ProtoMessage() {}

func (x *InfraAdminContributionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_infra_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfraAdminContributionConfig.ProtoReflect.Descriptor instead.
func (*InfraAdminContributionConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_infra_admin_proto_rawDescGZIP(), []int{0}
}

func (x *InfraAdminContributionConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *InfraAdminContributionConfig) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *InfraAdminContributionConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InfraAdminContributionConfig) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InfraAdminContributionConfig) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *InfraAdminContributionConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *InfraAdminContributionConfig) GetRenderMode() string {
	if x != nil {
		return x.RenderMode
	}
	return ""
}

func (x *InfraAdminContributionConfig) GetAppContext() string {
	if x != nil {
		return x.AppContext
	}
	return ""
}

func (x *InfraAdminContributionConfig) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type InfraAdminConfig struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	ApiBasePath   string                        `protobuf:"bytes,1,opt,name=api_base_path,json=apiBasePath,proto3" json:"api_base_path,omitempty"`
	Prefix        string                        `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Admin         *InfraAdminContributionConfig `protobuf:"bytes,3,opt,name=admin,proto3" json:"admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfraAdminConfig) Reset() {
	*x = InfraAdminConfig{}
	mi := &file_internal_contracts_infra_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfraAdminConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfraAdminConfig) ProtoMessage() {}

func (x *InfraAdminConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_infra_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfraAdminConfig.ProtoReflect.Descriptor instead.
func (*InfraAdminConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_infra_admin_proto_rawDescGZIP(), []int{1}
}

func (x *InfraAdminConfig) GetApiBasePath() string {
	if x != nil {
		return x.ApiBasePath
	}
	return ""
}

func (x *InfraAdminConfig) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *InfraAdminConfig) GetAdmin() *InfraAdminContributionConfig {
	if x != nil {
		return x.Admin
	}
	return nil
}

type GetAdminContributionInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminContributionInput) Reset() {
	*x = GetAdminContributionInput{}
	mi := &file_internal_contracts_infra_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminContributionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminContributionInput) ProtoMessage() {}

func (x *GetAdminContributionInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_infra_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminContributionInput.ProtoReflect.Descriptor instead.
func (*GetAdminContributionInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_infra_admin_proto_rawDescGZIP(), []int{2}
}

type GetAdminContributionOutput struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Enabled       bool                          `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Contribution  *InfraAdminContributionConfig `protobuf:"bytes,2,opt,name=contribution,proto3" json:"contribution,omitempty"`
	Error         string                        `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminContributionOutput) Reset() {
	*x = GetAdminContributionOutput{}
	mi := &file_internal_contracts_infra_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminContributionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminContributionOutput) ProtoMessage() {}

func (x *GetAdminContributionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_infra_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminContributionOutput.ProtoReflect.Descriptor instead.
func (*GetAdminContributionOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_infra_admin_proto_rawDescGZIP(), []int{3}
}

func (x *GetAdminContributionOutput) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GetAdminContributionOutput) GetContribution() *InfraAdminContributionConfig {
	if x != nil {
		return x.Contribution
	}
	return nil
}

func (x *GetAdminContributionOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_contracts_infra_admin_proto protoreflect.FileDescriptor

const file_internal_contracts_infra_admin_proto_rawDesc = "" +
	"\n" +
	"$internal/contracts/infra_admin.proto\x12\x1fworkflow.plugins.infra.admin.v1\"\x8a\x02\n" +
	"\x1cInfraAdminContributionConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06module\x18\x02 \x01(\tR\x06module\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12\x1f\n" +
	"\vrender_mode\x18\a \x01(\tR\n" +
	"renderMode\x12\x1f\n" +
	"\vapp_context\x18\b \x01(\tR\n" +
	"appContext\x12 \n" +
	"\vpermissions\x18\t \x03(\tR\vpermissions\"\xa3\x01\n" +
	"\x10InfraAdminConfig\x12\"\n" +
	"\rapi_base_path\x18\x01 \x01(\tR\vapiBasePath\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12S\n" +
	"\x05admin\x18\x03 \x01(\v2=.workflow.plugins.infra.admin.v1.InfraAdminContributionConfigR\x05admin\"\x1b\n" +
	"\x19GetAdminContributionInput\"\xaf\x01\n" +
	"\x1aGetAdminContributionOutput\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12a\n" +
	"\fcontribution\x18\x02 \x01(\v2=.workflow.plugins.infra.admin.v1.InfraAdminContributionConfigR\fcontribution\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05errorBKZIgithub.com/GoCodeAlone/workflow-plugin-infra/internal/contracts;contractsb\x06proto3"

var (
	file_internal_contracts_infra_admin_proto_rawDescOnce sync.Once
	file_internal_contracts_infra_admin_proto_rawDescData []byte
)

func file_internal_contracts_infra_admin_proto_rawDescGZIP() []byte {
	file_internal_contracts_infra_admin_proto_rawDescOnce.Do(func() {
		file_internal_contracts_infra_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_contracts_infra_admin_proto_rawDesc), len(file_internal_contracts_infra_admin_proto_rawDesc)))
	})
	return file_internal_contracts_infra_admin_proto_rawDescData
}

var file_internal_contracts_infra_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_contracts_infra_admin_proto_goTypes = []any{
	(*InfraAdminContributionConfig)(nil), // 0: workflow.plugins.infra.admin.v1.InfraAdminContributionConfig
	(*InfraAdminConfig)(nil),             // 1: workflow.plugins.infra.admin.v1.InfraAdminConfig
	(*GetAdminContributionInput)(nil),    // 2: workflow.plugins.infra.admin.v1.GetAdminContributionInput
	(*GetAdminContributionOutput)(nil),   // 3: workflow.plugins.infra.admin.v1.GetAdminContributionOutput
}
var file_internal_contracts_infra_admin_proto_depIdxs = []int32{
	0, // 0: workflow.plugins.infra.admin.v1.InfraAdminConfig.admin:type_name -> workflow.plugins.infra.admin.v1.InfraAdminContributionConfig
	0, // 1: workflow.plugins.infra.admin.v1.GetAdminContributionOutput.contribution:type_name -> workflow.plugins.infra.admin.v1.InfraAdminContributionConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_contracts_infra_admin_proto_init() }
func file_internal_contracts_infra_admin_proto_init() {
	if File_internal_contracts_infra_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_contracts_infra_admin_proto_rawDesc), len(file_internal_contracts_infra_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_contracts_infra_admin_proto_goTypes,
		DependencyIndexes: file_internal_contracts_infra_admin_proto_depIdxs,
		MessageInfos:      file_internal_contracts_infra_admin_proto_msgTypes,
	}.Build()
	File_internal_contracts_infra_admin_proto = out.File
	file_internal_contracts_infra_admin_proto_goTypes = nil
	file_internal_contracts_infra_admin_proto_depIdxs = nil
}
